
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 11:36:40 UTC 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 30;
  public static final int CONST = 3;
  public static final int GE = 20;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int MINUS = 15;
  public static final int RPAREN = 9;
  public static final int LT = 21;
  public static final int COMMA = 10;
  public static final int INC = 26;
  public static final int DIV = 17;
  public static final int PLUS = 14;
  public static final int IF = 34;
  public static final int DOT = 33;
  public static final int LE = 22;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 31;
  public static final int EQUAL = 25;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int NUMBER = 38;
  public static final int MOD = 18;
  public static final int IDENT = 41;
  public static final int VOID = 37;
  public static final int EQ = 23;
  public static final int COLON = 29;
  public static final int ELSE = 35;
  public static final int LBRACE = 5;
  public static final int ENUM = 4;
  public static final int READ = 12;
  public static final int CHARCONST = 39;
  public static final int RBRACE = 6;
  public static final int BOOLCONST = 40;
  public static final int PROG = 2;
  public static final int NE = 24;
  public static final int QUESTION = 28;
  public static final int DEC = 27;
  public static final int GT = 19;
  public static final int PRINT = 11;
  public static final int LENGTH = 32;
}

