
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 15 20:45:18 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 28;
  public static final int GE = 18;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 13;
  public static final int RPAREN = 7;
  public static final int LT = 19;
  public static final int COMMA = 8;
  public static final int INC = 24;
  public static final int DIV = 15;
  public static final int PLUS = 12;
  public static final int IF = 32;
  public static final int DOT = 31;
  public static final int LE = 20;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 29;
  public static final int EQUAL = 23;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int NUMBER = 36;
  public static final int MOD = 16;
  public static final int IDENT = 39;
  public static final int VOID = 35;
  public static final int EQ = 21;
  public static final int COLON = 27;
  public static final int LBRACE = 3;
  public static final int ELSE = 33;
  public static final int READ = 10;
  public static final int CHARCONST = 37;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 38;
  public static final int PROG = 2;
  public static final int NE = 22;
  public static final int QUESTION = 26;
  public static final int DEC = 25;
  public static final int GT = 17;
  public static final int PRINT = 9;
  public static final int LENGTH = 30;
}

